# Customize logging verbosity by package
logging:
  level:
    org.springframework: ERROR
    pt.jmnpedrosa.samples.springboot.restful: DEBUG

# Enable swagger in this environment
swagger.enabled: true
